# name: Build Docs

# on:
#   push:
#     branches:
#     - master

# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     name: Run Lint
#     steps:
#       - uses: actions/checkout@v1
#       - uses: borales/actions-yarn@v2.0.0
#         with:
#           cmd: install # will run `yarn install` command
#       - uses: borales/actions-yarn@v2.0.0
#         with:
#           cmd: run lint
#   build-deploy:
#     runs-on: ubuntu-18.04
#     steps:
#     - uses: actions/checkout@v1

#     - name: Setup Python
#       uses: actions/setup-python@v1
#       with:
#         python-version: '3.6'
#         architecture: 'x64'

#     - name: Install dependencies
#       run: |
#         python3 -m pip install --upgrade pip
#         python3 -m pip install mkdocs
#         python3 -m pip install mkdocs-material

#     - run: mkdocs build
    
#     - name: Deploy
#       uses: peaceiris/actions-gh-pages@v2
#       env:
#         ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#         PUBLISH_BRANCH: gh-pages
#         PUBLISH_DIR: ./site
